### ISSUE TITLE
repo link

### ISSUE THREAD

**Issue by florianhartig** [MarianSchoen/DTD#1]
In der readme steht devtools::install_github("spang-lab/DTD"), ist der link richtig oder sollte es MarianSchoen/DTD sein?

**Comment by MarianSchoen** [comment]
Ja, der devtools::install_github("spang-lab/DTD") link stimmt, dort ist ein Fork von devtools::install_github("MarianSchoen/DTD") zu finden. 
Mein Lehrstuhl hat darum gebeten, alle Projekte zentral zu sammeln, also verweis ich im readme direkt auf spang-lab.
